const {
  addPerson,
  editPerson,
  resetAttendance,
  updateAttendances,
  addGame,
  editGame,
  removeGame,
  addParticipants,
  removeParticipants,
} = require('./dml');
const {
  getPersons,
  getToday,
  getTodayByType,
  getPerson,
  getPersonsById,
  getGameDates,
  getGame,
  getGames,
  getGamesByDate,
  getPersonGames,
  getHistory,
} = require('./query');

module.exports = {
  addPerson,
  editPerson,
  resetAttendance,
  updateAttendances,
  addGame,
  editGame,
  removeGame,
  addParticipants,
  removeParticipants,
  getPersons,
  getToday,
  getTodayByType,
  getPerson,
  getPersonsById,
  getGameDates,
  getGame,
  getGames,
  getGamesByDate,
  getPersonGames,
  getHistory,
};
